# This is a config for E2B sandbox template.
# You can use template ID (xdu25gdn2ih39uw8c80w) or template name (buildfy-nextjs-buzzka-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("buildfy-nextjs-buzzka-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("buildfy-nextjs-buzzka-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('buildfy-nextjs-buzzka-test-2')

team_id = "5c30098f-16ca-4a93-bac3-7a861bd01c58"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "buildfy-nextjs-buzzka-test-2"
template_id = "xdu25gdn2ih39uw8c80w"
